config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies, only: [:index] do
    resources :showtimes, only: [:show]
  end

  resources :orders

  get '/movie/:id/orders' => 'orders#movie_order_review', as: 'movie_order_review'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :theater
  has_many :showtimes, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :showtime
  belongs_to :theater
  belongs_to :movie
  before_update :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_CREDIT_CARD_REGEX = /(^\d{15,16}$)/
  VALID_ZIP_CODE_REGEX = /(^\d{5}$)/
  VALID_CVV_REGEX = /(^\d{3}$)/

  validates :email, presence: true,
                    on: :update,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX,
                              message: "- that email doesn't look right to us, check it again please." }

  validates :credit_card, presence: true,
                          on: :update,
                          length: { maximum: 16 },
                          format: { with: VALID_CREDIT_CARD_REGEX,
                                    message: "- the card info doesn't look right to us. Check the length and make sure it's only numbers please." }

  validates :name, presence: true, on: :update
  validates :card_expiration_month, presence: true, on: :update
  validates :card_expiration_year,  presence: true, on: :update
  validates :cvv, presence: true,
                       on: :update,
                       length: { maximum: 3 },
                       format: { with: VALID_CVV_REGEX,
                                 message: "- CVV should only be 3 digits. No letters or extra numbers please."}
  validates :street_address, presence: true, on: :update
  validates :city, presence: true, on: :update
  validates :state, presence: true, on: :update
  validates :zip_code, presence: true,
                       on: :update,
                       length: { maximum: 5 },
                       format: { with: VALID_ZIP_CODE_REGEX,
                                 message: "- zip codes should only be 5 digits. No letters or extra numbers please."}
  validates :country, presence: true, on: :update

  private
    def downcase_email
      self.email = email.downcase
    end
end

app/models/showtime.rb
class Showtime < ActiveRecord::Base
  belongs_to :theater
  belongs_to :movie
  has_many :orders, dependent: :destroy

  def seats_remaining
    ticket_count = []
    theater_orders = Order.where(theater: self.theater)
    showtime_orders = theater_orders.where(showtime: self.id)

    showtime_orders.each do |order|
      ticket_count << order.tickets.to_i
    end
    tickets_sold = ticket_count.sum

    return self.theater.capacity - tickets_sold

    ticket_count.clear
  end
end

app/models/theater.rb
class Theater < ActiveRecord::Base
  has_many :movies, dependent: :destroy
  has_many :showtimes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.order(:title)
    if params[movies_path]
      date = params[movies_path][:date].to_datetime
      @showtimes = Showtime.where(start_time: ((date.beginning_of_day + 5.hours)..(date.end_of_day + 5.hours)))
    else
      @showtimes = Showtime.where(start_time: ((Date.today.beginning_of_day + 5.hours)..(Date.today.end_of_day + 5.hours)))
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order_and_movie, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
    @movies = Movie.order(:title)
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to edit_order_path(@order)
    else
      render 'new', errors: @order.errors
    end
  end

  def show
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Your purchase was successful.'
      OrderMailer.send_receipt(@order, @order.email).deliver_now
    else
      render 'edit'
    end
  end

  def destroy
    @order.destroy
    redirect_to movies_path, notice: 'Your order has been cancelled'
  end

  def movie_order_review
    @movie = Movie.find(params[:id])
  end

  private
    def set_order_and_movie
      @order = Order.find(params[:id])
      @movie = Movie.find(@order.movie_id)
    end

    def order_params
      params.require(:order).permit(:email, :name, :credit_card, :card_expiration_month, :card_expiration_year,
                                    :cvv, :tickets, :street_address, :city, :state, :zip_code, :country,
                                    :theater_id, :showtime_id, :movie_id)
    end
end

app/controllers/showtimes_controller.rb
class ShowtimesController < ApplicationController
  def show
    @showtime = Showtime.find(params[:id])
    @movie = Movie.find(params[:movie_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def verify_age(movie, showtime_id)
    age_params_hash = params[movie_showtime_path(movie.id, showtime_id)]
    if age_params_hash.nil?
      movie.rating == "R" || movie.rating == "PG-13" ? true : false
    end
  end

  def age_check_passes?(movie, showtime_id)
    age_params_hash = params[movie_showtime_path(movie.id, showtime_id)]
    if age_params_hash.nil?
      return true
    else
      birthdate_array = []
      age_day = age_params_hash[:age_day]
      age_month = age_params_hash[:age_month]
      age_year = age_params_hash[:age_year]
      birthdate_array << age_day << age_month << age_year
      birthdate_time = birthdate_array.join("/").to_time

      case movie.rating
      when "PG-13"
        13.years.ago.to_time >= birthdate_time ? true : false
      when "R"
        17.years.ago.to_time >= birthdate_time ? true : false
      end
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def ticket_price(showtime)
    case
    when showtime.start_time.hour <= 11
      return 7.5
    when showtime.start_time.hour > 11 && showtime.start_time.hour < 18
      return 10
    when showtime.start_time.hour >= 18
      return 9
    end
  end

  def order_subtotal(showtime, num_of_tickets)
    ticket_price(showtime) * num_of_tickets.to_i
  end

  def order_tax(showtime, num_of_tickets)
    (order_subtotal(showtime, num_of_tickets) * 0.0975).round(2)
  end

  def order_total(showtime, num_of_tickets)
    order_subtotal(showtime, num_of_tickets) + order_tax(showtime, num_of_tickets)
  end
end

app/helpers/showtimes_helper.rb
module ShowtimesHelper
  def format_showtime(showtime)
    showtime.start_time.hour < 12 ?
    "#{showtime.start_time.strftime("%A")} #{showtime.start_time.strftime("%-l:%M")}am" :
    "#{showtime.start_time.strftime("%A")} #{showtime.start_time.strftime("%-l:%M")}pm"
  end

  def format_showtime_without_day(showtime)
    showtime.start_time.hour < 12 ?
    "#{showtime.start_time.strftime("%-l:%M")}am" :
    "#{showtime.start_time.strftime("%-l:%M")}pm"
  end

  def sold_out(showtime)
    showtime.seats_remaining == 0 ? true : false
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LakeStreetCinema</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lora|Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <% unless flash.empty? %>
      <div class="flash-container">
        <%= render 'shared/flash_messages' %>
      </div>
    <% end %>

    <div class="body-panel">
      <div class="row">
        <div class="col-xs-12 text-center header-logo">
          <h1><%= link_to "Lake Street Cinema", root_url %></h1>

          <nav>
            <ul class="nav-links">
              <li><%= link_to "About us", "#" %></li>
              <li><%= link_to "Contact us", "#" %></li>
              <li><%= link_to "Orders", orders_path %></li>
            </ul>
          </nav>

          <hr />

        </div>
      </div>

      <%= yield %>

    </div>
    <footer>
      <div class="col-xs-12 text-center footer-logo">
        <p>Lake Street Cinemas</p>
      </div>
    </footer>
  </body>
</html>

app/views/movies/_movie_thumbnail.html.erb
<div class="movie-thumbnail-image-index text-center">
  <%= image_tag movie.image, alt: movie.title, class: "movie-image" %>
  <div class="movie-showtime-info">
    <h4 id="<%= dom_id movie %>_title"><%= movie.title %></h4>
    <div class="showtime-index" id="<%= dom_id movie %>_showtimes">
      <h4>Showtimes</h4>
      <% if showtimes.empty? %>
        <p>No showtimes scheduled today</p>
      <% else %>
        <% showtimes.each do |showtime| %>
          <% if showtime.movie == movie %>
            <div class="col-xs-6">
              <p>
                <% if sold_out(showtime) %>
                  <span class="sold-out-showtime">Sold Out</span>
                <% else %>
                  <%= link_to movie_showtime_path(movie, showtime), class: "showtime-link" do %>
                    <%= format_showtime_without_day(showtime) %>
                  <% end %>
                <% end %>
              </p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container">
  <div class="row col-xs-12 text-center now-showing-header">
    <h2>Now Showing</h2>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(movies_path, method: :get, html: { class: "select-showtime-date-form",
                                                      id: "select-showtime-date-form",
                                                      remote: true }) do |f| %>
        <%= f.select :date, [], {}, { class: "form-control select-showtime-date", id: "select-showtime-date" } do %>
          <% 8.times do |n| %>
            <%= content_tag(:option, "Showtimes for #{n.days.from_now.strftime("%A, %B %e, %Y")}",
            value: n.days.from_now.strftime("%e")) %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row movies-container">
    <% @movies.each do |movie| %>
      <div class="col-md-4 movie-thumbnail" id="<%= dom_id movie %>">
        <%= render 'movie_thumbnail', movie: movie, showtimes: @showtimes %>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/index.js.erb
<% @movies.each do |movie| %>
  $('#<%= dom_id movie %>').html('<%= escape_javascript(render 'movie_thumbnail',
                                                                     movie: movie, showtimes: @showtimes) %>');
<% end %>

$('.movies-container').animate({ opacity: '100' }, 1000);

app/views/orders/_edit_form.html.erb
<%= form_for order, html: { class: "edit-ticket-order-form" } do |f| %>
  <% if order.errors.any? %>
    <%= render "shared/errors", resource: order %>
  <% end %>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :email, class: "control-label" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :credit_card, "Credit Card", class: "control-label" %>
      <%= f.text_field :credit_card, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :name, "Name on Credit Card", class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group row">
      <div class="col-xs-12">
        <%= f.label :card_expiration_month, "Expiration Date", class: "control-label" %>
      </div>
      <div class="col-xs-6">
        <%= f.select :card_expiration_month,
                     ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
                     { prompt: "Select a month..." }, class: "form-control" %>
       </div>

      <div class="col-xs-6">
        <%= f.select :card_expiration_year, [], { prompt: "Select a year..." }, { class: "form-control" } do %>
          <% 11.times do |n| %>
            <%= content_tag(:option, (Time.now.year) + n) %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :cvv, "CVV (3 digits on back of card)", class: "control-label" %>
      <%= f.text_field :cvv, class: "form-control" %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :street_address, "Billing Street Address", class: "control-label" %>
      <%= f.text_field :street_address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :city, class: "control-label" %>
      <%= f.text_field :city, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :state, class: "control-label" %>
      <%= f.text_field :state, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :zip_code, "Zip Code", class: "control-label" %>
      <%= f.text_field :zip_code, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :country, class: "control-label" %>
      <%= f.text_field :country, class: "form-control" %>
    </div>
  </div>


  <div class="col-xs-12 form-group text-center">

    <hr />

    <%= f.submit "Place Order", class: "btn btn-primary submit-ticket-order-button" %>
    or
    <%= link_to "Cancel order", order, method: :delete,
                data: { confirm: 'Are you sure you want to cancel this order?' } %>
  </div>
<% end %>

app/views/orders/_form.html.erb
<%= form_for order do |f| %>
  <% if order.errors.any? %>
    <%= render "shared/errors", resource: order %>
  <% end %>

  <div class="form-group">
    <%= f.label 'How many tickets?' %>
    <%= f.select :tickets, [], {}, { class: "form-control" } do %>
      <% 1...(movie.theater.capacity).times do |number| %>
        <%= content_tag :option, (number + 1), value: (number + 1) %>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label 'Which showtime?' %>
    <%= f.select :showtime_id, options_from_collection_for_select(movie.theater.showtimes,
                                                               "id", "start_time"),
                                                               {}, { class: "form-control" } %>
  </div>

  <%= f.hidden_field :theater_id, value: movie.theater.id %>
  <%= f.hidden_field :movie_id, value: movie.id %>

  <div class="form-group pull-right">
    <%= f.submit "Order tickets", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/_new_form.html.erb
<%= form_for order do |f| %>
  <% if order.errors.any? %>
    <%= render "shared/errors", resource: order %>
  <% end %>

  <div class="form-group col-md-5 ticket-select-field">
    <%= f.select :tickets, [], {}, { class: "form-control" } do %>
      <% showtime.seats_remaining.times do |number| %>
        <%= content_tag :option, (number + 1), value: (number + 1) %>
      <% end %>
    <% end %>
  </div>

  <%= f.hidden_field :theater_id,  value: movie.theater.id %>
  <%= f.hidden_field :movie_id,    value: movie.id %>
  <%= f.hidden_field :showtime_id, value: params[:id] %>

  <div class="form-group">
    <%= f.submit "Order tickets", class: "btn btn-primary add-ticket-button" %>
  </div>
<% end %>

app/views/orders/_order_summary.html.erb
<div class="order-summary">
  <div class="row">
    <div class="col-xs-12">
      <p>
        <% if (@order.tickets).to_i > 1 %>
          <%= @order.tickets %> tickets for
        <% else %>
          <%= @order.tickets %> ticket for
        <% end %>
        <em><%= @movie.title %></em>
      </p>
      <div class="row">
        <div class="col-xs-12">
          <p>
            Theater number <%= @order.theater.number %> at
            <strong><%= format_showtime(@order.showtime) %></strong>
            <span class="pull-right"><%= number_to_currency(ticket_price(@order.showtime)) %> each</span>
          </p>
        </div>
      </div>
    </div>
  </div>

  <hr />

  <div class="row">
    <div class="col-xs-12 text-right">
      <p>Subtotal: <%= number_to_currency(order_subtotal(@order.showtime, @order.tickets)) %></p>
      <p>Tax: <%= number_to_currency(order_tax(@order.showtime, @order.tickets)) %></p>
      <p><strong>Total: <%= number_to_currency(order_total(@order.showtime, @order.tickets)) %></strong></p>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<div class="edit-order-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h3>Please review your order before purchasing</h3>

        <hr />

      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <h4>Your Order</h4>

        <hr />

        <%= render 'order_summary', order: @order, movie: @movie %>
      </div>

      <div class="col-xs-12">
        <div class="text-center">
          <h4>Please enter your email and credit card info for billing</h4>

          <hr />

        </div>
        <%= render 'edit_form', order: @order %>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">

  <div class="row text-center orders-table-type-header">
    <h3>All Orders</h3>

    <div class="row orders-index-header">
      <p>
        <%= link_to "View orders by movie", "#", id: "view-orders-by-movie" %>
      </p>
      <ul class="movie-order-review-list">
        <% @movies.each do |movie| %>
          <li><%= link_to movie.title, movie_order_review_path(movie), class: "movie-review-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row">
    <table class="table table-hover orders-table">
      <tr>
        <th>Movie</th>
        <th>Showtime</th>
        <th>Theater Number</th>
        <th>Number of Tickets</th>
        <th>Total (with tax)</th>
      </tr>
      <% @orders.each do |order| %>
        <tr>
          <td data-th="Movie">
            <%= link_to order_path(order), class: "order-table-link" do %>
              <%= order.movie.title %>
            <% end %>
          </td>
          <td data-th="Showtime">
            <%= link_to order_path(order), class: "order-table-link" do %>
              <%= format_showtime(order.showtime) %>
            <% end %>
          </td>
          <td data-th="Theater Number">
            <%= link_to order_path(order), class: "order-table-link" do %>
              <%= order.theater.number %>
            <% end %>
          </td>
          <td data-th="Number of Tickets">
            <%= link_to order_path(order), class: "order-table-link" do %>
              <%= order.tickets %>
            <% end %>
          </td>
          <td data-th="Total (with tax)">
            <%= link_to order_path(order), class: "order-table-link" do %>
              <%= number_to_currency(order_total(order.showtime, order.tickets)) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="row text-center">
    <p><%= link_to "<< Back to Movies", movies_path, class: "nav-links" %></p>
  </div>
</div>

app/views/orders/movie_order_review.html.erb
<div class="container">
  <div class="row text-center orders-table-type-header">
    <h3>Orders for <%= @movie.title %></h3>
  </div>
    <div class="row">
      <table class="table table-hover orders-table">
        <tr>
          <th>Showtime</th>
          <th>Theater Number</th>
          <th>Number of Tickets</th>
          <th>Total (with tax)</th>
        </tr>
        <% @movie.showtimes.each do |showtime| %>
          <% showtime.orders.each do |order| %>
            <tr>
              <td data-th="Showtime">
                <%= link_to order_path(order), class: "order-table-link" do %>
                  <%= format_showtime(order.showtime) %>
                <% end %>
              </td>
              <td data-th="Theater Number">
                <%= link_to order_path(order), class: "order-table-link" do %>
                  <%= order.theater.number %>
                <% end %>
              </td>
              <td data-th="Number of Tickets">
                <%= link_to order_path(order), class: "order-table-link" do %>
                  <%= order.tickets %>
                <% end %>
              </td>
              <td data-th="Total (with tax)">
                <%= link_to order_path(order), class: "order-table-link" do %>
                  <%= number_to_currency(order_total(order.showtime, order.tickets)) %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row text-center">
    <p><%= link_to "<< Back to All Orders", orders_path, class: "nav-links" %></p>
  </div>
</div>

app/views/orders/review.html.erb
<div class="container">
  <div class="row">
    <table class="table table-hover">
      <th>Number of Tickets</th>
      <th>Movie</th>
      <th>Showtime</th>
      <th>Theater Number</th>
      <th>Total (with tax)</th>
      <% @movie.showtimes.each do |showtime| %>
        <% if showtime.orders.length > 0 %>
          <% showtime.orders.each do |order| %>
            <tr>
              <td><%= order.tickets %></td>
              <td><%= order.movie.title %></td>
              <td><%= to_strftime(order.showtime) %></td>
              <td><%= order.theater.number %></td>
              <td><%= number_to_currency(order_total(order.showtime, order.tickets)) %></td>
            </tr>
          <% end %>
        <% else %>
          <div class="no-orders-message text-center">
            <h4>No orders yet for this film</h4>
          </div>
          <% break %>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <% if request.referrer == edit_order_url(@order) %>
    <div class="row">
      <div class="col-xs-12">
        <h3>Thank you for your order! You'll receive an email confirmation shortly.</h3>
        <p>Tickets are will call or you can print your order confirmation and present it to the ticket taker.</p>
        <h4>Your order:</h4>
      </div>
    </div>
  <% end %>

  <hr />

  <div class="row">
    <div class="col-xs-12">
      <%= render 'order_summary', order: @order, movie: @movie %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 text-center">
      <%= link_to "I'm Done", movies_path, class: "btn btn-primary back-to-movies-button" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>
    <%= pluralize(resource.errors.count, "error") %> prohibited this machine from being saved:
  </strong>
  <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><small><%= message %></small></li>
    <% end %>
  </ul>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, message| %>
  <% alert_type = "" %>
  <% if msg_type == 'success' %>
    <% alert_type = 'success' %>
  <% elsif msg_type == 'error' %>
    <% alert_type = 'danger' %>
  <% elsif msg_type == 'alert' %>
    <% alert_type = 'warning' %>
  <% elsif msg_type == 'notice' %>
    <% alert_type = 'warning' %>
  <% end %>
  <%= content_tag :div, message, class: "flash-container alert alert-#{alert_type}",
                                 id: "flash", role: "alert" %>
<% end %>

app/views/shared/errors.html.erb
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>
    <%= pluralize(resource.errors.count, "error") %> prohibited this machine from being saved:
  </strong>
  <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><small><%= message %></small></li>
    <% end %>
  </ul>
</div>

app/views/showtimes/_verify_age_popup.html.erb
<% if verify_age(movie, showtime_id) %>
  <div id="verifyAge" class="modal fade" role="dialog">
    <div class="modal-dialog verify-age-modal-dialog">
      <div class="modal-content verify-age-modal">
        <div class="modal-header text-center">
          <h4 class="modal-title">This movie is rated <%= movie.rating %>. Please verify your age.</h4>
        </div>
        <div class="modal-body">
          <%= form_for(movie_showtime_path(movie.id, showtime_id), method: :get) do |f| %>
            <div class="row text-center">
              <div class="form-group col-md-8 col-md-offset-2 col-xs-12">
                <%= f.label :age, "Select month", class: "control-label" %>
                <%= f.select :age_month,
                             ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
                             {}, class: "form-control" %>
              </div>

              <div class="form-group col-md-8 col-md-offset-2 col-xs-12">
                <%= f.label :age, "Select day", class: "control-label" %>
                <%= f.select :age_day, [], {}, { class: "form-control" } do %>
                  <% 31.times do |n| %>
                    <%= content_tag(:option, n + 1) %>
                  <% end %>
                <% end %>
              </div>

              <div class="form-group col-md-8 col-md-offset-2 col-xs-12">
                <%= f.label :age, "Select year", class: "control-label" %>
                <%= f.select :age_year, [], {}, { class: "form-control" } do %>
                  <% 100.times do |n| %>
                    <%= content_tag(:option, (Time.now.year) - n) %>
                  <% end %>
                <% end %>
              </div>
              <div class="form-group col-md-8 col-md-offset-2 col-xs-12">
                <%= f.submit "Verify Age", class: "btn btn-primary verify-age-button" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/showtimes/show.html.erb
<div class="container">
  <%= render 'verify_age_popup', movie: @movie, showtime_id: params[:id] %>

  <div class="row">
    <div class="col-md-3 col-xs-12 movie-thumbnail-image-show">
      <%= image_tag @movie.image, class: "img-responsive" %>
    </div>
    <div class="col-md-8 showtime-summary">
      <h3>
        <%= format_showtime(@showtime) %> showing for <%= @movie.title %> (<%= @movie.rating %>)
      </h3>
      <p>
        Director: <%= @movie.director %> | Genre: <%= @movie.genre %> | Runtime: <%= @movie.runtime %> min
      </p>
      <p>
        <%= @movie.synopsis %>
      </p>

      <hr />

      <% if age_check_passes?(@movie, params[:id]) %>
        <h4 class="reserve-tickets-header">
          Reserve your tickets for <%= @movie.title %>
          <small>(<%= @showtime.seats_remaining %> seats left)</small>
        </h4>
        <%= render 'orders/new_form', order: Order.new, movie: @movie, showtime: @showtime %>
      <% else %>
        <div class="not-old-enough-message">
          <h4>Sorry, you're not old enough to see this movie!</h4>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row text-center">
    <p><%= link_to "<< Back to Movies", movies_path, class: "nav-links" %></p>
  </div>
</div>